### ISSUE TITLE
Bootstrap HackDays for August 2022

### ISSUE THREAD

**Issue by rawkode** [rawkode-academy/hackdays#1]
- [x] Create notify group on Discord
- [x] Find 3 team captains to bootstrap process for people that want to contribute but are unsure how
- [x] Confirm submission deadline and requirements to enter
  - README
  - Public codebase
  - 5 minute demo video
- [ ] How do we mentor people that need assistance?
- [ ] How do people vote on Discord?

**Comment by rawkode** [comment]
Should we have a weekly "All Hands" on the Discord for questions and advice?

**Comment by icepuma** [comment]
Should or could we hijack the Standup on mondays?

**Comment by icepuma** [comment]
The question should be also: `How much time have people to vote on the projects?`, because maybe the people want to have look into the projects on their own.

I only know strawpoll.me for voting in cases like this. Maybe there is a better suited tool.

**Comment by icepuma** [comment]
The entry requirements should be at least a `README` and having the code publicly available. The video should be optional. Not everyone is capable or willing to do a demo video, I guess.

Should we give out some requirements for OSS licenses?

**Comment by icepuma** [comment]
The one thing I overthink is if the topic is too complicated or too nerdy? Are the instructions clear?

**Comment by icepuma** [comment]
I created a sample issue https://github.com/RawkodeAcademy/hackdays/issues/2

The label [hackdays-august-2022](https://github.com/RawkodeAcademy/hackdays/labels/hackdays-august-2022) is just a best guess. We can change it, if you want to have a different naming schema.

**Comment by icepuma** [comment]
I adjusted the information according to your and my input. Could you please read over and give a yay or nay :) Much obliged

**Comment by rawkode** [comment]
> Should or could we hijack the Standup on mondays?

We can add 10 mins on for a hackdays standup

> Should we give out some requirements for OSS licenses?

OSI approved?

> The one thing I overthink is if the topic is too complicated or too nerdy? Are the instructions clear?

Let's keep it as is and encourage conversations about ideas in the channel

**Comment by icepuma** [comment]
OSI approved sounds good.

One of the `Licenses that are "popular and widely-used or with strong communities"
` - section?
